colorScheme = "github"
defaultAppearance = "light"
autoSwitchAppearance = true
smartTOC = true
article.showTableOfContents = true
article.showAuthor = false
article.showPagination = false
list.showTableOfContents = true