name: Check Links
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          args: --verbose --no-progress "content/**/*.md" README.md
